INNUM_BUFFER_SIZE equ 5
SHNUM_BUFFER_SIZE equ 3
ACTION_BUFFER_SIZE equ 3
RESULT_BUFFER_SIZE equ 7
USERINPUT_BUFFER_SIZE equ 64
ARGUMENT_BUFFER_SIZE equ 16
FILENAME_BUFFER_SIZE equ 11

PROGRAM_ADDRESS equ 1000h
PROGRAM_LENGTH equ 65 ; In sectors, without boot sector
TABLE_SIZE equ 64
